### ISSUE TITLE
Mega aula 4

### ISSUE THREAD

**Issue by prof-daniel** [prof-daniel/aula4-branches#1]
O push realizado no começo da aula não deu certo devido a um conflito de nomes

**Comment by Nicolas-Granatelli** [comment]
Oi prof boa tarde o meu deu isso também 👎

**Comment by RafaelFDS1** [comment]
Tá acontecendo a mesma coisa comigo professor, como que a gente resolve?

**Comment by barba-scripts** [comment]
Aula DAD? pensava que era aula de artes 🤔
